[{"name": "test.test_file_count.FileCount.test_calls", "status": "passed", "message": "", "passed": true, "points": ["p02-06.1"], "backtrace": []}, {"name": "test.test_file_count.FileCount.test_first", "status": "passed", "message": "", "passed": true, "points": ["p02-06.1"], "backtrace": []}, {"name": "test.test_file_count.FileCount.test_main", "status": "failed", "message": "'0 \\t 0 \\t 0 \\t file0' != '0\\t0\\t0\\tfile0'\n- 0 \t 0 \t 0 \t file0\n+ 0\t0\t0\tfile0\n : Wrong result on line 0!", "passed": false, "points": ["p02-06.2"], "backtrace": ["  File \"C:\\Program Files\\Python311\\Lib\\unittest\\case.py\", line 57, in testPartExecutor\n    yield\n", "  File \"C:\\Program Files\\Python311\\Lib\\unittest\\case.py\", line 623, in run\n    self._callTestMethod(testMethod)\n", "  File \"C:\\Program Files\\Python311\\Lib\\unittest\\case.py\", line 579, in _callTestMethod\n    if method() is not None:\n       ^^^^^^^^\n", "  File \"C:\\Program Files\\Python Project\\P1\\PythonData-1\\Ã¸velser\\e26_file_count\\test\\test_file_count.py\", line 43, in test_main\n    self.assertEqual(line.strip(), \"0\\t0\\t0\\tfile%i\" % i,\n"]}]